### ISSUE TITLE
TypeError after updating "@angular-devkit/build-angular to 0.803.2

### ISSUE THREAD

**Issue by simdevmon** [ngx-translate/i18n-polyfill#60]
I use `"@ngx-translate/i18n-polyfill": "1.0.0"` together with Angular 8.2.4 and it is working fine so far with:

```
    "@angular-devkit/build-angular": "0.802.2",
    "@angular/cli": "^8.2.2",
```

When I update to and start my application with `ng serve --aot`

```
    "@angular-devkit/build-angular": "0.803.2",
    "@angular/cli": "^8.3.2",
```

I get the following error when trying to access the application in the browser:

```
ERROR Error: Uncaught (in promise): TypeError: this._input.charCodeAt is not a function
TypeError: this._input.charCodeAt is not a function
    at Tokenizer._advance (ngx-translate-i18n-polyfill.js:1256)
    at new Tokenizer (ngx-translate-i18n-polyfill.js:1111)
    at tokenize (ngx-translate-i18n-polyfill.js:1062)
    at Parser.parse (ngx-translate-i18n-polyfill.js:1909)
    at Xliff2Parser.parse (ngx-translate-i18n-polyfill.js:3382)
    at xliff2LoadToI18n (ngx-translate-i18n-polyfill.js:3359)
    at Function.load (ngx-translate-i18n-polyfill.js:6389)
    at new I18n (ngx-translate-i18n-polyfill.js:6939)
    at _createClass (core.js:30471)
    at _createProviderInstance (core.js:30425)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39679)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
```

![2019-09-03_14h06_22](https://user-images.githubusercontent.com/16277781/64171872-06e8b700-ce54-11e9-9330-42a456516cc8.png)

```
Angular CLI: 8.3.2
Node: 10.16.0
OS: win32 x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2
@angular-devkit/build-angular     0.803.2
@angular-devkit/build-optimizer   0.803.2
@angular-devkit/build-webpack     0.803.2
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.2
@angular/cdk                      8.1.4
@angular/cli                      8.3.2
@ngtools/webpack                  8.3.2
@schematics/angular               8.3.2
@schematics/update                0.803.2
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by wartab** [comment]
It's been a while, but I have the same issue since the upgrade to angular-cli 8.3.

**Comment by ibrcic** [comment]
I have the same issue, anyone found a solution?

**Comment by dschwank** [comment]
The `raw-loader` changed. You have to use `.default` when requiring the xlf file.

``````

See: https://github.com/angular/angular/issues/32333

**Comment by simdevmon** [comment]
Thank you @dschwank . This was working for me.

**Comment by lukengda** [comment]
The readme.md should note those changes. The raw-loader example here is just showing the 8.0.0 way. Maybe we should provide both versions for now, I just followed the instructions here in the repo and ran into this problem…

**Comment by saidsoualhi** [comment]
I get this error while this scenario, I'm setting the localeId with data retrieved from the backend API, when I remove the async/await this return value before promise completed.
Otherwise when I put the async/await it get the localeId but I get this erroe : Uncaught (in promise): TypeError: this._input.charCodeAt is not a function.

this is my app.module.ts file :
`const USER_SETTINGS = async (userSettingsService: UserSettingsService) => {
  let locale: string;
  await userSettingsService.getLocalId().then((userSettings) => {
    locale = userSettings.langague;
  });
  locale ? locale = locale : locale = RA_DEFAULT_LOCALE;
  console.log(locale) // 'fr' (in my case user test)
  return require('raw-loader!../i18n/messages.${locale}.xlf').default;
}`

`const RA_I18N_PROVIDERS = [
  I18n, {
    provide: TRANSLATIONS_FORMAT,
    useValue: `xlf`
  }, {
    provide: TRANSLATIONS,
    useFactory: USER_SETTINGS,
    deps: [UserSettingsService]
  }, {
    provide: LOCALE_ID,
    useValue: RA_DEFAULT_LOCALE
  }
];`

`providers: [
    ...,
    ...RA_I18N_PROVIDERS
  ],`
